from wtforms import Form, BooleanField, StringField, validators

class SegmentPrototypeForm(Form):
    ipa_group = StringField(u'IPA Group', [validators.InputRequired()])
    ipa_name = StringField(u'IPA Name', [validators.InputRequired()])
    ipa_symbol = StringField(u'IPA Symbol', [validators.Length(min=1, max=3)])
    ipa_manner = StringField(u'IPA Manner', [validators.InputRequired()])
    ipa_major_place = StringField(u'IPA Major Place', [validators.InputRequired()])
    ipa_minor_place = StringField(u'IPA Minor Place', [validators.InputRequired()])
    ipa_voice = StringField(u'IPA Voicing', [validators.InputRequired()])
    syllabic = BooleanField(u'±syl')
    consonantal = BooleanField(u'±cons')
    approximant = BooleanField(u'±approx')
    sonorant = BooleanField(u'±son')
    voice = BooleanField(u'±voice')
    spread_glottis = BooleanField(u'±spread')
    constricted_glottis = BooleanField(u'±constr')
    continuant = BooleanField(u'±cont')
    nasal = BooleanField(u'±nasal')
    strident = BooleanField(u'±strid')
    lateral = BooleanField(u'±lat')
    labial = BooleanField(u'±lab')
    round = BooleanField(u'±round')
    coronal = BooleanField(u'±cor')
    anterior = BooleanField(u'±ant')
    distributed = BooleanField(u'±dist')
    dorsal = BooleanField(u'±dors')
    back = BooleanField(u'±back')
    low = BooleanField(u'±low')
    tense = BooleanField(u'±tense')
    radical = BooleanField(u'±rad')
    laryngeal = BooleanField(u'±laryn')
    high = BooleanField(u'±high')